local saves={
    "gimp",
    "gnome-terminal",
    "gimp",
    "gvim",
    "gimp",
    "pidgin",
    "gnome-terminal",
    "pidgin",
    "gnome-terminal",
    "oowriter",
    "gvim advice.txt",
    "oowriter",
    "pidgin",
    "oowriter",
    "pidgin",
    "gvim",
    "pidgin",
    "gimp",
    "xvncviewer 10.42.1.1",
    "terminal",
    "",
    "gnome-terminal",
    "VirtualBox",
    "pidgin",
    "gvim",
    "oowriter",
    "pidgin",
    "gvim p10_p12_finances.txt",
    "pidgin",
    "",
    "gvim",
    "pidgin",
    "gnome-terminal",
    "gvim",
    "pidgin",
    "gvim travel.txt",
    "pidgin",
    "xvncviewer",
    "gvim",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "gimp",
    "xvncviewer 10.42.1.1",
    "gnumeric",
    "gvim",
    "pidgin",
    "gnome-terminal",
    "",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "VirtualBox",
    "pidgin",
    "oowriter",
    "gnome-terminal",
    "urxvt -rv -tr -sh 30 -ls +sb -vb -fn \034xft:Bitstream Vera Sans Mono:pixelsize=12\034",
    "bin/terminal",
    "urxvt -e sh",
    "urxvt -e 'sh --norc'",
    "",
    "oowriter",
    "xvncviewer 10.42.1.1",
    "gnome-terminal",
    "gvim",
    "recoll",
    "oowriter",
    "recoll",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "xvncviewer 10.42.1.1",
    "recoll",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "firefox",
    "hydrogen",
    "pidgin",
    "konqueror",
    "oowriter",
    "firefox",
    "gvim",
    "pidgin",
    "firefox",
    "gnome-terminal",
    "firefox",
    "wicd-client -n",
    "pidgin",
    "firefox",
    "pidgin",
    "firefox",
    "wicd-client -n",
    "gnome-terminal",
    "firefox",
    "wicd-client -n",
    "gvim",
    "firefox",
    "",
    "firefox",
    "audacity",
    "lmms",
    "firefox",
    "",
    "firefox",
    "audacity",
    "gnumeric",
    "",
    "firefox",
    "",
    "firefox",
    "pidgin",
    "firefox",
    "gnome-terminal",
    "gnumeric",
    "single",
    "oowriter",
    "firefox",
    "gvim",
    "pidgin",
    "oowriter",
    "firefox",
    "wicd-client -n",
    "firefox",
    "pidgin",
    "firefox",
    "gvim",
    "gnome-terminal",
    "firefox",
    "oowriter",
    "firefox",
    "iceweasel",
    "oowriter",
    "iceweasel",
    "oowriter",
    "pidgin",
    "iceweasel",
    "pidgin",
    "gvim",
    "gnumeric",
    "",
    "opera",
    "konqueror",
    "bin/ie6",
    "",
    "gnome-terminal",
    "gvim",
    "gimp",
    "konqueror",
    "gvim",
    "bin/ie6",
    "konqueror",
    "gvim",
    "",
    "icedove",
    "",
    "firefox",
    "gnome-terminal",
    "gnumeric",
    "gvim",
    "single",
    "",
    "gvim",
    "pidgin",
    "firefox",
    "konqueror",
    "",
    "pidgin",
    "",
    "gvim",
    "pidgin",
    "firefox",
    "konqueror",
    "pidgin",
    "gvim",
    "firefox",
    "gnumeric tmp/test.csv",
    "ekiga",
    "firefox",
    "pidgin",
    "icedove",
    "gnome-terminal",
    "firefox",
    "",
    "gnome-terminal",
    "alarm-clock",
    "ooimpress",
    "pidgin",
    "firefox",
    "acroread blah.pdf",
    "gnumeric",
    "firefox",
    "alarm-clock",
    "firefox",
    "gvim",
    "firefox",
    "gnome-terminal",
    "icedove",
    "xvncviewer 10.42.1.1",
    "icedove",
    "firefox",
    "gvim",
    "firefox",
    "pidgin",
    "firefox",
    "vmplayer",
    "xvncviewer 10.42.1.1",
    "pidgin",
    "firefox",
    "icedove",
    "firefox",
    "gnome-terminal",
    "icedove",
    "firefox",
    "pidgin",
    "firefox",
    "pidgin",
    "",
    "pidgin",
    "gvim",
    "firefox",
    "gaim",
    "firefox",
    "pidgin",
    "firefox",
    "xvkbd -text '\092CaF'",
    "vmplayer",
    "pidgin",
    "firefox",
    "pidgin",
    "",
    "firefox",
    "vmplayer",
    "pidgin",
    "firefox",
    "bin/ie6",
    "firefox",
    "gnome-terminal",
    "ie6",
    "gimp",
    "gvim",
    "pidgin",
    "firefox",
    "pidgin",
    "firefox",
    "gaim",
    "konqueror",
    "gvim",
    "",
    "gaim",
    "pidgin",
    "",
    "firefox",
    "pidgin",
    "firefox",
    "gnome-terminal",
    "gaim",
    "konqueror",
}
for k=table.getn(saves),1,-1 do query_history_push(saves[k]) end
